### PR TITLE
Add a matchable version of operand

### PR DESCRIPTION
**Pull request by TheZoq2**
Here is a proposal to a solution for #6. Adds the `OperandM` enum which is a copy of `Operand` but where everything is a reference and ConstRef/TypeRefs have been dereferenced to work with pattern matching.

It might also make sense to do something similar for other types, but in my current project, I aparently don't need it.

I'm not sold on the names `OperandM` and `.matchable()` but I'm not sure if there are any good alternatives...

### CODE REVIEW

**Comment by cdisselkoen** [comment]
Thanks for the suggestion!  Definitely an idea I hadn't thought of.

I might wait on this for a day or so to think about the names etc, and if any other types would want the same treatment.  Also it's not great that this is effectively cloning the `Operand` just to match on it (at least I think?) but maybe the ergonomics are worth it.

**Comment by TheZoq2** [comment]
>  Also it's not great that this is effectively cloning the Operand just to match on it (at least I think?) but maybe the ergonomics are worth it.

Yea, I agree that it's not the neatest solution ever. For me, the ergonomics make a fairly big difference, but I could also move this impl into my own project now that I think about it.

**Comment by cdisselkoen** [comment]
What about, as an alternative, adding an `as_constant()` method to `Operand` that goes like this:
```rust

impl Operand {
    pub fn as_constant(&self) -> Option<&Constant> {
        match self {
            Operand::ConstantOperand(cref) => Some(&cref),
            _ => None,
        }
    }
}
```

Then, the code for the example you give in the comments in this PR would look like:
```rust
  if let Some(Constant::Float(Float::Double(val))) = op.as_constant() {
      val
  } else {
      Err(Error::NonConstantInput)?
  };
```

This allows the match using only one `match` statement but without introducing a new struct or effectively cloning the `Operand`.  Would this work for your use case?

**Comment by TheZoq2** [comment]
Oh yea, that's a much cleaner idea! I think I even use the same pattern in my code somewhere :)

I can update the PR tomorrow :)

**Comment by cdisselkoen** [comment]
Not a problem, I'll just push the `as_constant()` method here to master.  

Thanks for bringing this up, this is going to be a good improvement!

**Comment by cdisselkoen** [comment]
Pushed as 78075a3.

**Pull request closed without merging**
