### PR TITLE
Add `llvm_version` function (resolves #13)

### LINKED ISSUE #13: Query for LLVM version?
Is there a way to ask `llvm-ir` for the LLVM version it was configured for?

I am imagining something like:
```rust
pub fn llvm_version() -> u32 {
    if cfg!(feature = "llvm-8") {
        return 8;
    }
    ...
}
```

Clearly, this could be handled in the caller (since it chose the feature). But I am wondering if there is a way to handle this without having to do extra work in the caller.

### PR DESCRIPTION
**Pull request by smoelius**
Resolves #13

At the risk of over-engineering a simple function, how's this?

(I'm happy to make any changes you prefer.)

### CODE REVIEW

**Review by cdisselkoen — COMMENTED** [review]
LGTM.  Minor thing -- can you add a doc comment for the `llvm_version` function?

**Comment by smoelius** [comment]
Here too, I'm happy to adjust wording etc. if you have a preference.

**Review by cdisselkoen — APPROVED** [review]
Looks great, thanks!

**Comment by smoelius** [comment]
Thank you!

**Pull request merged**
