### PR TITLE
Add function for adding named structs

### PR DESCRIPTION
**Pull request by TheZoq2**
I finally got around to bumping my version up to 0.7 as per #8, however, a few of my tests require adding named structs to the types list which I found no way of doing. I cobbled together this, but I'm not sure if it's the most optimal way.

If this makes sense, I can add some doc comments as well

### CODE REVIEW

**Comment by cdisselkoen** [comment]
After thinking about this some, I think I have a slightly different proposed patch.

As noted in comments in `types.rs` (around line 537), one intended behavior of `Types` is that "if you happen to want a type which wasn't encountered when parsing the `Module` ... it will still construct that `Type` and give you a `TypeRef`."  Our implementation of `.named_struct()` violates this intention by not giving you a `TypeRef` if the struct doesn't already exist in the `Module`.  So I think we should change the behavior of `.named_struct()` to never fail.  Users who really want to know if a named struct exists in the `Module` can use `.named_struct_def()` instead, which is probably better anyway.

As a result, we no longer need to adjust `named_struct_types.map` in the `add_named_struct_def()` method -- we can actually simply reuse the implementation of that method from `TypesBuilder`, which also panics if you try to redefine an already-existing struct (which seems good to me).  In case someone _actually_ wants to redefine an existing struct, I suppose we should also add a method to _remove_ a named struct definition.

I've pushed my proposed version of the patch to the `adding-named-typedefs` branch in the main repo (commit f712cd7) -- can you take a look and see if it works for your use case?

**Comment by TheZoq2** [comment]
From the sound of it, that seems like a great approach. I did feel like it was kind of strange to have it "default" to a newly constructed type for most types, but not structs. I'll have a closer look at changing my code on monday, but I'll close this PR for now

**Comment by TheZoq2** [comment]
I tested it now and looks like it works flawlessly for my needs, thanks :)

**Comment by cdisselkoen** [comment]
The `adding-named-typedefs` branch has now been merged to master.

**Pull request closed without merging**
